name: chem
channels:
  - david_baddeley
  - anaconda
  - conda-forge
  - schrodinger
  - psi4
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - ambit=0.3
  - apbs=1.5
  - asn1crypto=1.3.0
  - astor=0.8.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1
  - bleach=3.1.0
  - blinker=1.4
  - boost=1.68.0
  - boost-cpp=1.68.0
  - boto=2.49.0
  - boto3=1.12.12
  - botocore=1.15.12
  - bz2file=0.98
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.1.1
  - cachetools=3.1.1
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - chemps2=1.8.9
  - click=7
  - cryptography=2.8
  - cudatoolkit=9.2
  - cudnn=7.6.5
  - cupti=9.2.148
  - cupy=6.0.0
  - cycler=0.10.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - dkh=1.2
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.6
  - fastrlock=0.4
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gast=0.3.3
  - gau2grid=1.3.1
  - gdma=2.2.6
  - gettext=0.19.8.1
  - glew=2.0.0
  - glib=2.58.3
  - gmp=6.1.2
  - google-auth=1.11.2
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.1.8
  - grpcio=1.27.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - intel-openmp=2020
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - jmespath=0.9.4
  - joblib=0.14.1
  - jpeg=9b
  - jsonpickle=1.2
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - ld_impl_linux-64=2.33.1
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libiconv=1.15
  - libint=1.2.1
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxc=4.3.4
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.31.0
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mengine=1
  - mistune=0.8.4
  - mkl=2020
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mock=4.0.1
  - more-itertools=8.2.0
  - mpeg_encode=1
  - mtz2ccp4_px=1
  - mysql-connector-c=6.1.11
  - mysqlclient=1.4.6
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - nccl=1.3.5
  - ncurses=6.2
  - networkx=2.4
  - ninja=1.9.0
  - notebook=6.0.3
  - numba=0.48.0
  - numpy=1.18.1
  - numpy-base=1.18.1
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1
  - opt_einsum=3.1.0
  - packaging=20.1
  - pandas=1.0.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.1
  - patsy=0.5.1
  - pbr=5.4.1
  - pcre=8.43
  - pdfminer.six=20181108
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=20.0.2
  - pixman=0.34.0
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.4
  - pthread-stubs=0.3
  - ptyprocess=0.6.0
  - py=1.8.1
  - py-boost=1.67.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycairo=1.19.0
  - pycparser=2.19
  - pycryptodome=3.8.2
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
#  - pyro=3.16
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - pytest=5.0.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=1.3.1
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.6.0
  - rdkit=2019.03.2
  - readline=7
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - rigimol=1.3
  - rsa=4
  - runipy=0.1.5
  - s3transfer=0.3.3
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - send2trash=1.5.0
  - setuptools=45.2.0
  - simint=0.7
  - sip=4.19.8
  - six=1.14.0
  - smart_open=1.9.0
  - sortedcontainers=2.1.0
  - sqlite=3.31.1
  - statsmodels=0.11.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchvision=0.4.2
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - typing=3.6.4
  - typing_extensions=3.7.4.1
  - umap-learn=0.3.10
  - urllib3=1.25.8
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xlrd=1.2.0
  - xlsxwriter=1.2.8
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7

  - pip:
    - astunparse==1.6.3
    - bert-serving-client==1.10.0
    - bert-serving-server==1.10.0
    - bitstring==3.1.6
    - cairocffi==1.1.0
    - cairosvg==2.4.2
    - category-encoders==2.1.0
    - chainer==7.2.0
    - chainer-chemistry==0.7.0
    - cssselect2==0.2.2
    - docopt==0.6.2
    - gputil==1.4.0
    - h5py==2.10.0
    - livelossplot==0.4.2
    - pipreqs==0.4.10
    - pysmiles==1.0.0
    - stanfordnlp==0.2.0
    - tinycss2==1.0.2
    - yarg==0.1.9

